### ISSUE TITLE
Doubts about GeometricBilinear Implementation

### ISSUE THREAD

**Issue by ehsankiakojouri** [Qualcomm-AI-research/geometric-algebra-transformer#4]
Regarding the Geometric bilinears, paper mentions :
![image](https://github.com/Qualcomm-AI-research/geometric-algebra-transformer/assets/44782241/32934508-ec30-4dc9-86a1-307975d4e77f)
showing x and y to be the same for geometric product and join operation. 
However, in the GeometricBilinear class: https://github.com/Qualcomm-AI-research/geometric-algebra-transformer/blob/b101736ea293796176cc09dd7d5456773e65a95c/gatr/layers/mlp/geometric_bilinears.py#L14
 4 Equilinears are defined. If x and y are the same for both join and geometric product operator, the shouldn't the corresponding code be like the following?
   
```
        # EquiLinear Layer
        left, _ = self.linear_left(multivectors, scalars=scalars)
        right, _ = self.linear_right(multivectors, scalars=scalars)

        # GP
        gp_outputs = geometric_product(left, right)

        # Equivariant join
        join_outputs = equivariant_join(left, right, reference_mv)

        # Output linear
        outputs_mv = torch.cat((gp_outputs, join_outputs), dim=-2)
        outputs_mv, outputs_s = self.linear_out(outputs_mv, scalars=scalars)
```

**Comment by johannbrehmer** [comment]
Hi,

good catch!

Indeed, here the paper description is not accurate. Both versions in principle define expressive architectures. However, we believe that it makes more sense to use two independent equivariant linear maps for the join and the GP: the version implemented in the repository is in our opinion better than the simpler equation in the paper.

Apologies for the confusion. We can't update the NeurIPS paper anymore, but we will discuss updating this in the arXiv version.

Thanks,
Johann
